import type {
  ProjectBaseline,
  ProjectGraphEdge,
  ProjectGraphNode,
  ProjectMetric,
  ProjectOwner,
} from '@shared/api.interface';

function legacyOwners(name: string): ProjectOwner[] {
  if (!name || name === '待指定') return [];
  return name.split('/').map((item) => ({
    apaasUserId: '',
    name: item.trim(),
  }));
}

export function buildStaticNodes(): ProjectGraphNode[] {
  return [
    {
      id: 'hw-gen1',
      title: '一代头戴',
      subtitle: '现有产品 / 问题复现基线',
      lane: 'hardware',
      kind: 'hardware',
      status: 'released',
      owners: legacyOwners('项目组'),
      progress: 100,
      version: 'GEN-1',
      startDate: '2026-06-16',
      deadline: '2026-06-30',
      x: 90,
      y: 80,
      tags: ['一代', '基线', '驱动适配'],
      summary:
        '一代头戴作为二代适配和问题复现基线，重点保留 SD 卡、OTA、录音、ZMQ 传输等历史问题链路。',
      nextAction: '只保留必须复现的问题，避免继续在一代上扩散新开发。',
      risks: ['历史问题口径分散', '二代复现条件不完全一致'],
      linkedIds: ['bug-sdcard-gen1', 'ota-gen1'],
    },
    {
      id: 'hw-gen2',
      title: '二代头戴',
      subtitle: '核心板 / 头环 / CMOS / OTA',
      lane: 'hardware',
      kind: 'hardware',
      status: 'testing',
      owners: legacyOwners('李禧彤 / 钟睿'),
      progress: 82,
      version: 'GEN-2',
      startDate: '2026-07-03',
      deadline: '2026-07-17',
      x: 380,
      y: 80,
      tags: ['二代', '核心板', '结构', 'CMOS'],
      summary:
        '依据"第二代头戴"表格整理：核心板改版、头环结构、相机连接、CMOS/FPC、电池、OTA 和九轴 IMU 已形成二代主线。',
      nextAction:
        '把已完成事项收敛为验收基线，继续跟踪相机连接与电池相关改进。',
      risks: ['相机连接稳定性仍需硬件验证', '电池结构与电源接口需统一'],
      linkedIds: ['core-board-gen2', 'headband-gen2', 'camera-bug-gen2'],
    },
    {
      id: 'hw-gen21',
      title: '2.1 代头戴',
      subtitle: '当前改板 / 体积与电源优化',
      lane: 'hardware',
      kind: 'hardware',
      status: 'active',
      owners: legacyOwners('李禧彤'),
      progress: 35,
      version: 'GEN-2.1',
      startDate: '2026-07-21',
      deadline: '2026-08-04',
      x: 670,
      y: 80,
      tags: ['2.1代', '改板', '电源管理', 'CMOS稳定性'],
      summary:
        '当前 2.1 代只聚焦四件事：修改当前头戴 bug、增加电源管理、缩小体积、提高 CMOS 连接稳定性。',
      nextAction: '先完成 2.1 代改板方案冻结，再进入打样与回板验证。',
      risks: ['改动集中在硬件，验证周期较长', 'CMOS 连接器稳定性需要实测'],
      linkedIds: [
        'gen21-bugfix',
        'gen21-power',
        'gen21-size',
        'gen21-cmos-stability',
      ],
    },
    {
      id: 'bug-sdcard-gen1',
      title: 'SD 卡写入失败 bug',
      subtitle: '一代问题 / 二代复测',
      lane: 'integration',
      kind: 'risk',
      status: 'blocked',
      owners: legacyOwners('吕丰平'),
      progress: 35,
      version: 'BUG-SD-001',
      startDate: '2026-07-17',
      deadline: '2026-07-31',
      x: 90,
      y: 260,
      tags: ['一代', 'SD卡', '等待复现'],
      summary:
        '该 bug 是一代头戴问题，计划在二代头戴上测试出同样问题后再着手解决。',
      nextAction: '更新固件，问题出现时拉日志，不要直接重启。',
      risks: ['无法稳定复现', '可能与写入速度或 SD 卡寿命有关'],
      linkedIds: ['hw-gen1'],
    },
    {
      id: 'ota-gen1',
      title: '头戴 OTA 升级',
      subtitle: '一代能力沉淀',
      lane: 'software',
      kind: 'software',
      status: 'released',
      owners: legacyOwners('袁皓'),
      progress: 100,
      version: 'OTA-GEN1',
      startDate: '2026-07-01',
      deadline: '2026-07-15',
      x: 90,
      y: 400,
      tags: ['OTA', '固件升级'],
      summary: '自动从服务器烧录固件更新，作为后续二代 OTA 方案基础。',
      nextAction: '保留为二代电脑端 OTA 的能力输入。',
      risks: [],
      linkedIds: ['hw-gen1'],
    },
    {
      id: 'core-board-gen2',
      title: '二代核心板改版',
      subtitle: '100 片加工 / 8 片测试',
      lane: 'integration',
      kind: 'hardware',
      status: 'passed',
      owners: legacyOwners('李禧彤'),
      progress: 100,
      version: 'GEN2-CORE',
      startDate: '2026-06-25',
      deadline: '2026-07-09',
      x: 380,
      y: 260,
      tags: ['核心板', '打样', '已完成'],
      summary:
        '第二代头戴核心板改版并打样生产，包含嘉立创加工和快递到货时间；首批加工 100 片，贴片 8 片测试。',
      nextAction: '将已验证的问题列表迁移到 2.1 代改板 checklist。',
      risks: [],
      linkedIds: ['hw-gen2'],
    },
    {
      id: 'headband-gen2',
      title: '二代头戴头环结构',
      subtitle: '调节机构 / 适配不同头围',
      lane: 'integration',
      kind: 'hardware',
      status: 'passed',
      owners: legacyOwners('钟睿'),
      progress: 100,
      version: 'GEN2-RING',
      startDate: '2026-06-23',
      deadline: '2026-07-07',
      x: 380,
      y: 400,
      tags: ['结构', '头环', '已完成'],
      summary:
        '已修改二代头戴调节机构，可适配不同头围；后续方案不再依赖松紧带。',
      nextAction: '作为 2.1 代缩小体积和电池仓设计的结构约束。',
      risks: [],
      linkedIds: ['hw-gen2'],
    },
    {
      id: 'camera-bug-gen2',
      title: 'RGB 相机连接 bug',
      subtitle: 'FPC 连接座不稳',
      lane: 'integration',
      kind: 'risk',
      status: 'review',
      owners: legacyOwners('钟睿 / 李禧彤'),
      progress: 75,
      version: 'GEN2-CAM-CONNECT',
      startDate: '2026-07-10',
      deadline: '2026-07-24',
      x: 380,
      y: 540,
      tags: ['相机连接', 'FPC', '结构卡紧'],
      summary:
        'RGB 相机连接 bug 已定位为核心板 FPC 连接座连接不稳；临时方案通过结构卡紧，后续需重新设计带卡扣连接器。',
      nextAction: '并入 2.1 代 CMOS 连接稳定性改进。',
      risks: ['临时结构卡紧不是最终量产方案'],
      linkedIds: ['hw-gen2', 'gen21-cmos-stability'],
    },
    {
      id: 'cmos-fpc-gen2',
      title: '完全集成 CMOS 的 FPC',
      subtitle: '双 CMOS + 按键 + 九轴 IMU',
      lane: 'integration',
      kind: 'hardware',
      status: 'active',
      owners: legacyOwners('李禧彤 / 钟睿'),
      progress: 55,
      version: 'GEN2-FPC-CMOS',
      startDate: '2026-07-20',
      deadline: '2026-08-03',
      x: 380,
      y: 680,
      tags: ['FPC', 'CMOS', '九轴IMU'],
      summary: '设计单条 FPC 集成两块 CMOS，并加入按键与九轴 IMU。',
      nextAction: '根据板框安装方案进入 layout 与装配验证。',
      risks: ['FPC 板框与装配测试仍需闭环'],
      linkedIds: ['hw-gen2', 'gen21-cmos-stability'],
    },
    {
      id: 'imu-test-gen2',
      title: '当前头戴 + 九轴 IMU 测试',
      subtitle: 'VIO + 九轴 IMU',
      lane: 'software',
      kind: 'test',
      status: 'passed',
      owners: legacyOwners('王昊 / 徐子谦 / 钟睿'),
      progress: 100,
      version: 'GEN2-IMU9',
      startDate: '2026-07-20',
      deadline: '2026-08-03',
      x: 380,
      y: 820,
      tags: ['九轴IMU', 'VIO', 'SLAM'],
      summary:
        '九轴 IMU 滤波及校准后，加速度计与陀螺仪数据较之前六轴更平滑，SLAM 已完成运行验证。',
      nextAction: '暂不融合地磁计，仅预留接口。',
      risks: ['室内金属和电流会干扰地磁计'],
      linkedIds: ['hw-gen2'],
    },
    {
      id: 'ota-usb-gen2',
      title: 'OTA 电脑更新',
      subtitle: 'USB 访问设备网页',
      lane: 'software',
      kind: 'software',
      status: 'active',
      owners: legacyOwners('吕丰平'),
      progress: 45,
      version: 'GEN2-OTA-PC',
      startDate: '2026-07-21',
      deadline: '2026-08-04',
      x: 380,
      y: 960,
      tags: ['OTA', 'USB', '网页更新'],
      summary:
        '通过 USB 线连接电脑并访问设备网页，进入配网页面和固件 OTA 页面。',
      nextAction: '完善电脑端 OTA 页面和异常恢复流程。',
      risks: ['用户操作流程需要进一步简化'],
      linkedIds: ['hw-gen2'],
    },
    {
      id: 'gen21-bugfix',
      title: '修改当前头戴 bug',
      subtitle: '2.1 代当前事项',
      lane: 'integration',
      kind: 'issue',
      status: 'active',
      owners: legacyOwners('李禧彤'),
      progress: 35,
      version: 'GEN2.1-BUGFIX',
      startDate: '2026-07-20',
      deadline: '2026-08-03',
      x: 670,
      y: 260,
      tags: ['2.1代', '改板', 'bug修复'],
      summary: '收敛当前头戴遗留 bug，作为 2.1 代改板的第一目标。',
      nextAction: '整理 bug checklist 并确认每项的硬件改动位置。',
      risks: ['历史 bug 可能未完全结构化'],
      linkedIds: ['hw-gen21'],
    },
    {
      id: 'gen21-power',
      title: '增加电源管理',
      subtitle: '电池取电 / 充电 / 显示',
      lane: 'integration',
      kind: 'hardware',
      status: 'active',
      owners: legacyOwners('李禧彤'),
      progress: 30,
      version: 'GEN2.1-POWER',
      startDate: '2026-07-21',
      deadline: '2026-08-04',
      x: 670,
      y: 400,
      tags: ['2.1代', '电源管理', '电池'],
      summary:
        '增加电源管理能力，结合电池取电板、电池充电板、电池显示和电池仓结构修改。',
      nextAction: '统一取电、充电和主板接口定义。',
      risks: ['电源路径与结构空间同时受限'],
      linkedIds: ['hw-gen21'],
    },
    {
      id: 'gen21-size',
      title: '缩小体积',
      subtitle: '结构空间收敛',
      lane: 'integration',
      kind: 'hardware',
      status: 'planned',
      owners: legacyOwners('李禧彤'),
      progress: 15,
      version: 'GEN2.1-SIZE',
      startDate: '2026-07-21',
      deadline: '2026-08-04',
      x: 670,
      y: 540,
      tags: ['2.1代', '结构', '小型化'],
      summary: '在二代头环结构基础上进一步压缩体积，减少外部转接和结构冗余。',
      nextAction: '明确必须保留的安装孔、FPC 走线和电池仓空间。',
      risks: ['体积缩小可能影响散热和装配容差'],
      linkedIds: ['hw-gen21', 'headband-gen2'],
    },
    {
      id: 'gen21-cmos-stability',
      title: '提高 CMOS 连接稳定性',
      subtitle: '连接器 / FPC / 防松结构',
      lane: 'integration',
      kind: 'hardware',
      status: 'active',
      owners: legacyOwners('李禧彤'),
      progress: 40,
      version: 'GEN2.1-CMOS',
      startDate: '2026-07-21',
      deadline: '2026-08-04',
      x: 670,
      y: 680,
      tags: ['2.1代', 'CMOS', '连接稳定性'],
      summary:
        '针对二代 RGB 相机连接不稳定问题，2.1 代需要从连接器、FPC 与结构限位上提高 CMOS 连接稳定性。',
      nextAction: '确认是否采用带卡扣连接器，并完成 FPC/板框协同设计。',
      risks: ['连接稳定性必须依赖实物振动和插拔测试'],
      linkedIds: ['hw-gen21', 'camera-bug-gen2', 'cmos-fpc-gen2'],
    },
  ];
}

export function buildStaticEdges(): ProjectGraphEdge[] {
  return [
    edge('hw-gen1', 'hw-gen2', '代际演进', false),
    edge('hw-gen2', 'hw-gen21', '改板收敛', true),
    edge('hw-gen1', 'bug-sdcard-gen1', '历史问题', true),
    edge('hw-gen1', 'ota-gen1', '能力沉淀', false),
    edge('hw-gen2', 'core-board-gen2', '硬件基线', false),
    edge('hw-gen2', 'headband-gen2', '结构基线', false),
    edge('hw-gen2', 'camera-bug-gen2', '连接问题', true),
    edge('hw-gen2', 'cmos-fpc-gen2', 'FPC 改进', true),
    edge('hw-gen2', 'imu-test-gen2', '算法验证', false),
    edge('hw-gen2', 'ota-usb-gen2', '软件能力', false),
    edge('camera-bug-gen2', 'gen21-cmos-stability', '并入2.1', true),
    edge('cmos-fpc-gen2', 'gen21-cmos-stability', '设计输入', true),
    edge('headband-gen2', 'gen21-size', '结构约束', false),
    edge('hw-gen21', 'gen21-bugfix', '当前事项', true),
    edge('hw-gen21', 'gen21-power', '当前事项', true),
    edge('hw-gen21', 'gen21-size', '当前事项', true),
    edge('hw-gen21', 'gen21-cmos-stability', '当前事项', true),
  ];
}

export function buildStaticMetrics(nodes: ProjectGraphNode[]): ProjectMetric[] {
  const hardwareCount: number = nodes.filter(
    (node: ProjectGraphNode) => node.lane === 'hardware',
  ).length;
  const activeCount: number = nodes.filter(
    (node: ProjectGraphNode) =>
      node.status === 'active' ||
      node.status === 'testing' ||
      node.status === 'review',
  ).length;
  const blockedCount: number = nodes.filter(
    (node: ProjectGraphNode) => node.status === 'blocked',
  ).length;
  const gen21Count: number = nodes.filter((node: ProjectGraphNode) =>
    node.tags.includes('2.1代'),
  ).length;

  return [
    {
      key: 'hardware',
      label: '硬件代际',
      value: String(hardwareCount),
      tone: 'neutral',
    },
    {
      key: 'active',
      label: '推进中',
      value: String(activeCount),
      tone: 'good',
    },
    {
      key: 'gen21',
      label: '2.1代事项',
      value: String(gen21Count),
      tone: 'warning',
    },
    {
      key: 'blocked',
      label: '阻塞/等待',
      value: String(blockedCount),
      tone: blockedCount > 0 ? 'danger' : 'good',
    },
  ];
}

export function buildStaticBaselines(): ProjectBaseline[] {
  return [
    {
      id: 'baseline-gen1',
      name: '一代头戴问题复现基线',
      hardwareVersion: 'GEN-1',
      softwareVersion: 'OTA / SD / ZMQ 历史链路',
      status: '历史基线',
      releaseDate: '2026-06-30',
    },
    {
      id: 'baseline-gen2',
      name: '二代头戴验证基线',
      hardwareVersion: 'GEN-2',
      softwareVersion: '核心板 / 头环 / CMOS / 九轴 IMU',
      status: '测试验收',
      releaseDate: '2026-07-31',
    },
    {
      id: 'baseline-gen21',
      name: '2.1 代当前改板基线',
      hardwareVersion: 'GEN-2.1',
      softwareVersion: 'bug / 电源管理 / 小型化 / CMOS 稳定性',
      status: '进行中',
      releaseDate: '2026-08-04',
    },
  ];
}

function edge(
  source: string,
  target: string,
  label: string,
  critical: boolean,
): ProjectGraphEdge {
  return {
    id: `${source}-${target}`,
    source,
    target,
    label,
    critical,
  };
}
